export const popularMakes = [
  "Audi",
  "Chirey",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Fiat",
  "Ford",
  "Chevrolet",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jeep",
  "Kia",
  "Land Rover",
  "Lincoln",
  "Mazda",
  "Mercedes-Benz",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Peugeot",
  "RAM",
  "Renault",
  "SEAT",
  "Smart",
  "Subaru",
  "Suzuki",
  "Toyota",
  "Volkswagen",
  "Volvo",
];
export const popularModelsOfMakes = [
  {
    make: "Cadillac",
    models: [
      "Escalade",
      "XT5",
      "CT5",
      "XT6",
      "XT4",
      "CT4",
      "CTS",
      "ATS",
      "SRX",
      "XTS",
      "DTS",
      "ELR",
      "DeVille",
      "Seville",
      "Eldorado",
      "Fleetwood",
      "Allante",
      "Brougham",
      "Cimarron",
      "Catera",
      "XLR",
      "STS",
      "BLS",
      "Sixty Special",
      "Series 62",
      "Calais",
      "Series 75",
      "Coupe de Ville",
      "Series 61",
      "Sedan de Ville",
    ],
  },
  {
    make: "Chevrolet",
    models: [
      "Silverado",
      "Equinox",
      "Camaro",
      "Malibu",
      "Corvette",
      "Trax",
      "Traverse",
      "Colorado",
      "Bolt EV",
      "Tahoe",
      "Suburban",
      "Impala",
      "Spark",
      "Blazer",
      "Trailblazer",
      "Sonic",
      "Express",
      "Cruze",
      "Volt",
      "Beat",
      "Aveo",
      "Onix",
      "Captiva",
      "Orlando",
      "Avalanche",
      "Monte Carlo",
      "Cobalt",
      "HHR",
      "Tracker",
      "Cavalier",
    ],
  },
  {
    make: "Chirey",
    models: [
      "Tiggo 8",
      "Arrizo 6",
      "Tiggo 7",
      "Arrizo 5",
      "Tiggo 5x",
      "Arrizo GX",
      "Arrizo 8",
      "Tiggo 4",
      "Tiggo 3x",
      "Tiggo 2",
      "Arrizo EX",
      "QQ",
      "Cowin",
      "Fulwin",
      "Eastar",
      "Karry",
      "V5",
      "Rely",
      "A3",
      "M1",
      "G5",
      "G3",
      "E5",
      "E3",
      "A5",
      "A1",
      "QQ6",
      "QQ3",
      "Bonus",
      "Kimo",
    ],
  },
  {
    make: "Dodge",
    models: [
      "Challenger",
      "Charger",
      "Durango",
      "Grand Caravan",
      "Journey",
      "Ram 1500",
      "Viper",
      "Avenger",
      "Caliber",
      "Dart",
      "Nitro",
      "Ram 2500",
      "Ram 3500",
      "Dakota",
      "Magnum",
      "Neon",
      "Stratus",
      "Intrepid",
      "Dynasty",
      "Stealth",
      "Shadow",
      "Spirit",
      "Daytona",
      "Aries",
      "Diplomat",
      "Monaco",
      "St. Regis",
      "Ramcharger",
      "Omni",
      "600",
    ],
  },
  {
    make: "Fiat",
    models: [
      "500",
      "Panda",
      "Tipo",
      "500X",
      "500L",
      "Uno",
      "Argo",
      "Cronos",
      "Toro",
      "Strada",
      "Mobi",
      "Grand Siena",
      "Palio",
      "Punto",
      "Linea",
      "Bravo",
      "Doblo",
      "Fiorino",
      "Qubo",
      "Ducato",
      "124 Spider",
      "Sedici",
      "Freemont",
      "Viaggio",
      "Ottimo",
      "Siena",
      "Albea",
      "Idea",
      "Multipla",
      "Brava",
    ],
  },
  {
    make: "Ford",
    models: [
      "F-150",
      "Mustang",
      "Explorer",
      "Escape",
      "Ranger",
      "Fusion",
      "Edge",
      "Expedition",
      "Bronco",
      "EcoSport",
      "Focus",
      "Fiesta",
      "Transit",
      "Taurus",
      "GT",
      "Flex",
      "Thunderbird",
      "Mondeo",
      "Ka",
      "Figo",
      "Endeavour",
      "Everest",
      "Territory",
      "Falcon",
      "Shelby GT500",
      "Super Duty",
      "Crown Victoria",
      "Escort",
      "Contour",
      "Probe",
    ],
  },
  {
    make: "Honda",
    models: [
      "Civic",
      "Accord",
      "CR-V",
      "HR-V",
      "Pilot",
      "Ridgeline",
      "Odyssey",
      "Fit",
      "Insight",
      "Passport",
      "City",
      "Amaze",
      "WR-V",
      "BR-V",
      "Jazz",
      "Brio",
      "Mobilio",
      "e",
      "N-Box",
      "N-One",
      "N-WGN",
      "S660",
      "Vezel",
      "StepWGN",
      "Freed",
      "Grace",
      "Jade",
      "Shuttle",
      "Legend",
      "Integra",
    ],
  },
  {
    make: "Hyundai",
    models: [
      "Elantra",
      "Tucson",
      "Santa Fe",
      "Sonata",
      "Kona",
      "Palisade",
      "Venue",
      "Accent",
      "Creta",
      "i10",
      "i20",
      "i30",
      "Verna",
      "Aura",
      "Alcazar",
      "Grand i10 Nios",
      "Xcent",
      "Santro",
      "Veloster",
      "Nexo",
      "Ioniq",
      "Genesis",
      "Equus",
      "Azera",
      "Entourage",
      "Veracruz",
      "Tiburon",
      "XG350",
      "Trajet",
      "Terracan",
    ],
  },
  {
    make: "Jeep",
    models: [
      "Wrangler",
      "Grand Cherokee",
      "Cherokee",
      "Compass",
      "Renegade",
      "Gladiator",
      "Patriot",
      "Liberty",
      "Commander",
      "Wagoneer",
      "Comanche",
      "CJ",
      "Willys",
      "Forward Control",
      "DJ",
      "Jeepster",
      "J-Series",
      "C-Series",
      "Scrambler",
      "Grand Wagoneer",
      "Dispatcher",
      "Honcho",
      "CJ-5",
      "CJ-6",
      "CJ-7",
      "CJ-8",
      "CJ-10",
      "Jeepster Commando",
      "CJ-3B",
      "CJ-3A",
    ],
  },
  {
    make: "Kia",
    models: [
      "Forte",
      "Sportage",
      "Soul",
      "Telluride",
      "Sorento",
      "Optima",
      "Seltos",
      "Rio",
      "Stinger",
      "K5",
      "Sedona",
      "Niro",
      "Carnival",
      "Cadenza",
      "K900",
      "Ceed",
      "Picanto",
      "Stonic",
      "Mohave",
      "Cerato",
      "Carens",
      "Rondo",
      "Quoris",
      "Venga",
      "Opirus",
      "Borrego",
      "Magentis",
      "Amanti",
      "Enterprise",
    ],
  },
  {
    make: "Mazda",
    models: [
      "Mazda3",
      "CX-5",
      "Mazda6",
      "CX-30",
      "CX-9",
      "MX-5 Miata",
      "CX-3",
      "Mazda2",
      "CX-8",
      "CX-7",
      "MX-30",
      "Mazda5",
      "RX-8",
      "Tribute",
      "MPV",
      "Protege",
      "Mazdaspeed3",
      "RX-7",
      "Millenia",
      "929",
      "CX-4",
      "CX-60",
      "CX-80",
      "Atenza",
      "Axela",
      "Demio",
      "Verisa",
      "Premacy",
      "Biante",
      "Bongo",
    ],
  },
  {
    make: "Mitsubishi",
    models: [
      "Outlander",
      "Mirage",
      "Eclipse Cross",
      "Outlander Sport",
      "Lancer",
      "RVR",
      "Pajero",
      "Xpander",
      "Triton",
      "Montero Sport",
      "ASX",
      "Delica",
      "i-MiEV",
      "Attrage",
      "Galant",
      "Endeavor",
      "Grandis",
      "Diamante",
      "Eclipse",
      "3000GT",
      "Colt",
      "Carisma",
      "Space Star",
      "Raider",
      "Chariot",
      "L200",
      "Sigma",
      "eK",
      "Town Box",
    ],
  },
  {
    make: "Nissan",
    models: [
      "Rogue",
      "Altima",
      "Sentra",
      "Murano",
      "Kicks",
      "Pathfinder",
      "Frontier",
      "Maxima",
      "Versa",
      "LEAF",
      "Armada",
      "Titan",
      "GT-R",
      "370Z",
      "NV200",
      "Juke",
      "X-Trail",
      "Qashqai",
      "Patrol",
      "Navara",
      "March",
      "Micra",
      "Sunny",
      "Almera",
      "Tiida",
      "Teana",
      "Sylphy",
      "Serena",
      "Elgrand",
    ],
  },
  {
    make: "Peugeot",
    models: [
      "208",
      "3008",
      "2008",
      "308",
      "5008",
      "108",
      "508",
      "Expert",
      "Partner",
      "Rifter",
      "Traveller",
      "Boxer",
      "4008",
      "RCZ",
      "iOn",
      "207",
      "307",
      "407",
      "607",
      "1007",
      "4007",
      "206",
      "205",
      "405",
      "605",
      "806",
      "106",
      "309",
      "406",
      "807",
      "306",
    ],
  },
  {
    make: "Renault",
    models: [
      "Clio",
      "Captur",
      "Megane",
      "Kadjar",
      "Scenic",
      "Koleos",
      "Talisman",
      "Arkana",
      "Zoe",
      "Twingo",
      "Trafic",
      "Master",
      "Kangoo",
      "Sandero",
      "Duster",
      "Logan",
      "Kwid",
      "Symbol",
      "Twizy",
      "Espace",
      "Laguna",
      "Latitude",
      "Fluence",
      "Wind",
      "Vel Satis",
      "Avantime",
      "Modus",
      "Thalia",
      "Safrane",
    ],
  },
  {
    make: "Seat",
    models: [
      "Leon",
      "Ibiza",
      "Arona",
      "Ateca",
      "Tarraco",
      "Alhambra",
      "Mii",
      "Toledo",
      "Altea",
      "Cordoba",
      "Exeo",
      "Malaga",
      "Ronda",
      "Fura",
      "Marbella",
      "Terra",
      "Inca",
      "Arosa",
      "133",
      "127",
      "Panda",
      "Trans",
      "600",
      "850",
      "124",
      "128",
      "131",
      "132",
      "1200",
      "1430",
      "1500",
    ],
  },
  {
    make: "Suzuki",
    models: [
      "Swift",
      "Vitara",
      "SX4",
      "Jimny",
      "Alto",
      "Ignis",
      "Baleno",
      "S-Cross",
      "Ciaz",
      "Ertiga",
      "XL7",
      "Celerio",
      "Wagon R",
      "Dzire",
      "Spacia",
      "Hustler",
      "Every",
      "Landy",
      "Solio",
      "Lapin",
      "Splash",
      "Kizashi",
      "Grand Vitara",
      "Reno",
      "Forenza",
      "Aerio",
      "Verona",
      "X-90",
      "Esteem",
      "Sidekick",
    ],
  },
  {
    make: "Toyota",
    models: [
      "Camry",
      "RAV4",
      "Corolla",
      "Highlander",
      "Tacoma",
      "4Runner",
      "Sienna",
      "Tundra",
      "Prius",
      "C-HR",
      "Yaris",
      "Land Cruiser",
      "Avalon",
      "Sequoia",
      "Venza",
      "Supra",
      "Mirai",
      "Corolla Cross",
      "Agya",
      "Innova",
      "Fortuner",
      "Hilux",
      "Hiace",
      "Rush",
      "Alphard",
      "Crown",
      "Etios",
      "Glanza",
      "Urban Cruiser",
    ],
  },
  {
    make: "Volkswagen",
    models: [
      "Golf",
      "Tiguan",
      "Polo",
      "Passat",
      "Jetta",
      "Atlas",
      "Arteon",
      "T-Roc",
      "ID.4",
      "Taos",
      "Touareg",
      "Beetle",
      "CC",
      "Eos",
      "e-Golf",
      "Scirocco",
      "Phaeton",
      "Touran",
      "Sharan",
      "Caddy",
      "Amarok",
      "Crafter",
      "Multivan",
      "California",
      "Gol",
      "Voyage",
      "Saveiro",
      "Fox",
      "SpaceFox",
      "Suran",
    ],
  },
];
export const storiesLinks = [
  "https://www.facebook.com/seminuevossabomotors/videos/931426444972377",
  "https://www.facebook.com/seminuevossabomotors/videos/872476570193860",
  "https://www.facebook.com/seminuevossabomotors/videos/190600839404001",
];
