export const popularMakes = [
  "Chevrolet",
  "Nissan",
  "Volkswagen",
  "Ford",
  "Honda",
  "Toyota",
  "BMW",
  "Dodge",
  "Kia",
  "Mazda",
  "Audi",
  "Hyundai",
  "Jeep",
  "Suzuki",
  "Cadillac",
  "Chery",
  "Fiat",
  "Mercedes-Benz",
  "Mitsubishi",
  "Peugeot",
  "Renault",
  "Seat",
];

export const vehicles = [
  {
    id: 1,
    name: "Hyundai Accent Mid",
    make: "Sedan",
    year: 2018,
    cylinders: 4,
    horsepower: 121,
    torque: 111,
    fuelType: "Gasoline",
    fuelCapacity: 100,
    imageUrl: "/hyundaiaccent2018v2-resized.png",
    manualUrl: "https://carmanuals2.com/d/113504",
  },
  {
    id: 2,
    name: "Mercedes ML 350",
    make: "Mercedes Benz",
    year: 2008,
    cylinders: 6,
    horsepower: 268,
    torque: 258,
    fuelType: "Gasoline",
    fuelCapacity: 25.1,
    imageUrl: "/MercedesML350.png",
    manualUrl:
      "https://www.manualslib.com/download/102061/Mercedes-Benz-2002-M-Class.html",
  },
  {
    id: 3,
    name: "Beat Itz Std",
    make: "Chevrolet",
    year: 2019,
    cylinders: 4,
    horsepower: 77,
    torque: 74,
    fuelType: "Gasoline",
    fuelCapacity: 35.6,
    imageUrl: "/beatitz2019.png",
    manualUrl:
      "https://my.gm.com.mx/content/dam/gmownercenter/gmna/gmmx/dynamic/manuals/2020/chevrolet/beat/es/Chevrolet_2020_beat.pdf",
  },
];
